### ISSUE TITLE
eChronos build fixes

### ISSUE THREAD

**Issue by leepike** [GaloisInc/smaccmpilot-stm32f4#18]
- Eliminate the need for RAMSES_PATH.mk and PRJ_CMD.mk in the build.
  But maybe add an warning if the path doesn't exist.
- Figure out the status of and integrate the AADL bootloader stuff (addresses, debug).
- Eliminate the Makefile warnings in `src/smaccm-flight/platform-fmu24/standalone_flight_echronos` --- e.g., the `mv` errors.

**Comment by leepike** [comment]
Also,

* Add the `image.px4` target to the Makefile in `standalone_flight_echronos`, and make sure the required Python scripts are copied in.

**Comment by podhrmic** [comment]
Now it fails on a circularity check.  @acfoltzer and @leepike know what needs to happen

**Comment by podhrmic** [comment]
Closing since it is already resolved in master.
