### ISSUE TITLE
Implement altitude estimator

### ISSUE THREAD

**Issue by podhrmic** [GaloisInc/smaccmpilot-stm32f4#23]
To improve the quality of the altitude estimation, we need to fuse multiple sensors together. We're borrowing the implementation from Paparazzi autopilot.

## Sensors
1. lidar
2. baro
3. accelerometer

## How it works
This estimator is based entirely on callbacks, but again - because we are running all sensors at the same frequency, we can change this into one loop (maybe with some `new_data_available` checks).
**NOTE:** we are using `USE_VFF_EXTENDED` so keep that in mind while reading the code

It uses 1D Kalman filter, defined here: https://github.com/paparazzi/paparazzi/blob/master/sw/airborne/subsystems/ins/vf_extended_float.c

```
/**
 * @file subsystems/ins/vf_extended_float.c
 *
 * Extended vertical filter (in float).
 *
 * Estimates altitude, vertical speed, accelerometer bias
 * and barometer offset.
 *
 * X = [ z zdot accel_bias baro_offset ]
 *
```

1. init filter: https://github.com/paparazzi/paparazzi/blob/master/sw/airborne/subsystems/ins/vf_extended_float.c#L85
2. Upon accel measurements propagate them:
```
/**
 * Propagate the filter in time.
 *
 * F = [ 1 dt -dt^2/2 0
 *       0  1 -dt     0
 *       0  0   1     0
 *       0  0   0     1 ];
 *
 * B = [ dt^2/2 dt 0 0]';
 *
 * Q = [ Qzz   0          0         0
 *       0     Qzdotzdot  0         0
 *       0     0          Qbiasbias 0
 *       0     0     0    0         Qoffoff ];
 *
 * Qzz =  VFF_EXTENDED_ACCEL_NOISE * DT_VFILTER * DT_VFILTER / 2.
 * Qzdotzdot =  VFF_EXTENDED_ACCEL_NOISE * DT_VFILTER
 *
 * Xk1 = F * Xk0 + B * accel;
 *
 * Pk1 = F * Pk0 * F' + Q;
 */
```
3. Baro update function: https://github.com/paparazzi/paparazzi/blob/master/sw/airborne/subsystems/ins/vf_extended_float.c#L181
```
/**
 * Update sensor "with" offset (baro).
 *
 * H = [1 0 0 -1];
 * // state residual
 * y = rangemeter - H * Xm;
 * // covariance residual
 * S = H*Pm*H' + R;
 * // kalman gain
 * K = Pm*H'*inv(S);
 * // update state
 * Xp = Xm + K*y;
 * // update covariance
 * Pp = Pm - K*H*Pm;
 */
```
4. Lidar update function: https://github.com/paparazzi/paparazzi/blob/master/sw/airborne/subsystems/ins/vf_extended_float.c#L245
```
/**
 * Update sensor "without" offset (gps, sonar)
 * H = [1 0 0 0];
 * // state residual
 * y = rangemeter - H * Xm;
 * // covariance residual
 * S = H*Pm*H' + R;
 * // kalman gain
 * K = Pm*H'*inv(S);
 * // update state
 * Xp = Xm + K*y;
 * // update covariance
 * Pp = Pm - K*H*Pm;
 */
```
Indeed both functions are called with different noise (this is explained in `ins_int.c`, see below). Callbacks are defined as follows:

### Baro callback
Here: https://github.com/paparazzi/paparazzi/blob/master/sw/airborne/subsystems/ins/ins_int.c#L317

* waits to init baro (so we are starting at zero alt)
*  calls `vff_update_baro()`

### Lidar callback
Here it is called *sonar* callback: https://github.com/paparazzi/paparazzi/blob/master/sw/airborne/subsystems/ins/ins_int.c#L440

### Accel callback
We are propagating measured accel: https://github.com/paparazzi/paparazzi/blob/master/sw/airborne/subsystems/ins/ins_int.c#L502
* here is the propagate function: https://github.com/paparazzi/paparazzi/blob/master/sw/airborne/subsystems/ins/ins_int.c#L272
* derotate the accel
* call `vff_propagate`

**Comment by acfoltzer** [comment]
Do we want to derotate the lidar and sonar altitudes as well? It doesn't look like paparazzi does, but since we'll need the rotation state estimate anyway, perhaps we should?

**Comment by acfoltzer** [comment]
Is the baro offset still useful even if we're never trying to measure it? Does the state eventually update enough through other measurements that the offset becomes accurate?

**Comment by podhrmic** [comment]
Yes we do want to do the derotation, because in practice the measured and derotated altitudes differ in up to 15%. Here is the paparazzi code (it is bundled inside the lidar driver): https://github.com/paparazzi/paparazzi/blob/master/sw/airborne/modules/lidar/lidar_lite.c#L144 

And indeed similar for the sonar.

I think we still want to know the baro offset - because we use it when we get a baro measurement, see here: https://github.com/paparazzi/paparazzi/blob/master/sw/airborne/subsystems/ins/vf_extended_float.c#L185

Without the offset the baro measurements would be less accurate.

**Comment by acfoltzer** [comment]
Okay, so this is implemented on the `px4flow` branch. I realize now how the baro offset fits into the filter, but now I'm wondering more about the accel bias. The accel output that we're putting into the altitude estimator has already been calibrated, so maybe we could just drop this field from the state vector?

**Comment by podhrmic** [comment]
hmm, good point. For the time being I would keep it as is though, and if we really have accel measurements without bias, the `accel_bias` state will converge to zero. I suspect the bias will be different for z-axis and maybe not fully removed in the attitude estimation module.
