### ISSUE TITLE
Change calibration for accelerometer

### ISSUE THREAD

**Issue by acfoltzer** [GaloisInc/smaccmpilot-stm32f4#29]
Rather than subtracting a g out of the accelerometer, we should figure out the bias when it is static and flat, and subtract those bits out of the raw register data we read from the MPU6000. As it is, we're subtracting 9.8 from the Z acceleration, even when that axis is no longer down!

**Comment by acfoltzer** [comment]
And remember to subtract 9.8 out from the derotated accel in the altitude estimator.

**Comment by acfoltzer** [comment]
@podhrmic I have merged this in, before I close the ticket though could you write up some documentation about how to do the accelerometer calibration so other folks can do it on their vehicles?

**Comment by podhrmic** [comment]
Documentation in progress, so far it still waits for the new attitude estimator - once finished I ll change the documentation accordingly. First changes are already there http://smaccmpilot.org/software/preflight.html
