### ISSUE TITLE
GCS --verbose flag no longer works

### ISSUE THREAD

**Issue by agacek** [GaloisInc/smaccmpilot-stm32f4#32]
In the master branch the --verbose flag to the gcs.sh script no longer works.

**Comment by agacek** [comment]
Looks like some verbose output is being written to a csv file in the same directory. Is there a way to see the raw bytes that are coming and going over the serial line like before? This was sometimes useful for debugging, so it would be nice to have an option to enable it.

**Comment by acfoltzer** [comment]
It looks like the csv line in the script was missing a trailing `\`, so the arguments were getting swallowed. Back to normal now.
