### ISSUE TITLE
Alternate 'hacker' GCS

### ISSUE THREAD

**Issue by agacek** [GaloisInc/smaccmpilot-stm32f4#35]
For the phase 3 demo we would like the GCS to have a different 'skin' for the attacker. Is there any easy way we could make the background black or something and change the other text to still be readable? We want  to convey that all the same information is there, but it's somehow a different system.

**Comment by acfoltzer** [comment]
Should be able to do this fairly easily.

**Comment by acfoltzer** [comment]
With the latest master, try http://localhost:8080/elm2.html

It's not the greatest-looking theme, but is at least distinct from the normal one. I can probably go in and tweak aspects of it if you have requests.

**Comment by agacek** [comment]
Looks good. I'm sure we'll tweak things in Virgina based on how readable
things are on the big projectors.

-Andrew
