### ISSUE TITLE
Elm2 HUD depends on external resource

### ISSUE THREAD

**Issue by agacek** [GaloisInc/smaccmpilot-stm32f4#40]
The elm2 HUD depends on a resource from `fonts.googleapis.com`. This causes it to fail to load when working on an isolated demo.

https://github.com/GaloisInc/smaccmpilot-stm32f4/blob/master/src/smaccm-comm-client/web/bootstrap-3.3.4-dist/css/bootstrap-cyborg.min.css#L1

**Comment by acfoltzer** [comment]
Fixed in cfe3c03. Good catch!
