### ISSUE TITLE
smaccm-mavlink build scripts don't work on linux

### ISSUE THREAD

**Issue by pchickey** [GaloisInc/smaccmpilot-stm32f4#8]
The invocation of `split` in https://github.com/GaloisInc/smaccmpilot-stm32f4/blob/master/src/smaccm-mavlink/Makefile#L34-L35 works with BSD `split` found on the mac, but not with GNU `split` found on linux.

**Comment by jameysharp** [comment]
What would you think of updating the .cabal file from the Python code generator instead of from shell? The code generator already knows what list of modules it generated, and has nicer text processing tools available.

**Comment by pchickey** [comment]
we now use a terrible little python program to generate this file.
